### ISSUE TITLE
Heading Fails change to plain text

### ISSUE THREAD

**Issue by JacquelineOmollo** [unitymakesus/justgetsimple#72]
- [x] H2 If you are new to the Fragile X community, we welcome 
- [x] ~H2 We are a group of committed volunteers and family~
- [x] H5  2 empty tags
- [x] H4 2:00 pm, recurring every other Monday.

**Comment by andrewmarino** [comment]
@JacquelineOmollo I ended up marking that second H2 ("We are a group") as acceptable.

**Comment by JacquelineOmollo** [comment]
Done
